#include <stdio.h>

/*
 * Identificador extremadamente largo (>500 caracteres). C11 solo
 * garantiza significancia hasta 63 caracteres en identificadores
 * externos y 4095 en total (Anexo B), pero muchas herramientas
 * (resaltadores, linters, generadores de tablas ASCII) truncan o
 * rompen con nombres así de largos.
 */
int contador_de_intentos_fallidos_de_login_del_usuario_actual_en_el_sistema_de_autenticacion_academico_de_la_universidad_nacional_de_rio_negro_para_la_materia_programacion_1_durante_el_cuatrimestre_actual_sin_contar_los_intentos_bloqueados_por_el_firewall_perimetral_ni_los_intentos_realizados_desde_direcciones_ip_marcadas_como_sospechosas_por_el_sistema_de_deteccion_de_intrusos_institucional_version_dos_punto_cero = 0;

int
main(void)
{
    contador_de_intentos_fallidos_de_login_del_usuario_actual_en_el_sistema_de_autenticacion_academico_de_la_universidad_nacional_de_rio_negro_para_la_materia_programacion_1_durante_el_cuatrimestre_actual_sin_contar_los_intentos_bloqueados_por_el_firewall_perimetral_ni_los_intentos_realizados_desde_direcciones_ip_marcadas_como_sospechosas_por_el_sistema_de_deteccion_de_intrusos_institucional_version_dos_punto_cero += 1;
    printf("%d\n", contador_de_intentos_fallidos_de_login_del_usuario_actual_en_el_sistema_de_autenticacion_academico_de_la_universidad_nacional_de_rio_negro_para_la_materia_programacion_1_durante_el_cuatrimestre_actual_sin_contar_los_intentos_bloqueados_por_el_firewall_perimetral_ni_los_intentos_realizados_desde_direcciones_ip_marcadas_como_sospechosas_por_el_sistema_de_deteccion_de_intrusos_institucional_version_dos_punto_cero);
    return 0;
}
